channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.8.2
- pip
- pip:
  - mlflow
  - scikit-learn
  - transformers
  - torchtext
  - torchvision
  - torch>=1.9.0
  - pandas
  - datasets
